# Setup
title:               Vijay Kumar
tagline:             'Understandable notes'
description:         ''
url:                 https://vijay-kumar-hb.github.io
baseurl:             '/methods-quant/'
paginate:            5
permalink:           pretty
markdown:            kramdown
kramdown:
  hard_wrap: true

# About/contact
author:
  name:              Vijay Kumar
  url:               
  email:             vijay[.]kumar@hb.se

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
